name: Update Release Notes

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Release Notes
        id: release-notes
        run: |
          # Collect commit messages since the last release
          LAST_TAG=$(git describe --abbrev=0 --tags)
          COMMIT_MESSAGES=$(git log --pretty=format:'%s' --no-merges $LAST_TAG..HEAD)

          # Format commit messages as release notes
          VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_NOTES=$(echo "$COMMIT_MESSAGES" | sed -e "s/^/ - $VERSION: /")

          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Update README
        run: |
          # Replace existing release notes with new ones
          sed -i '0,/^## Release Notes/{s/^## Release Notes.*/## Release Notes/}' README.md
          sed -i "/## Release Notes/a $(echo -e '\n\n'${{ steps.release-notes.outputs.notes }})" README.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add README.md
          git commit -m "Update release notes [skip ci]"
          git push
